[package]
name = "paddler"
version = "0.10.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = "4.9.0"
askama = "0.12.1"
askama_actix = "0.14.0"
async-trait = "0.1.83"
clap = { version = "4.5.20", features = ["derive"] }
crossterm = "0.28.1"
env_logger = "0.11.5"
futures = "0.3.31"
futures-util = { version = "0.3.31", features = ["tokio-io"] }
log = "0.4.22"
mime_guess = "2.0.5"
pingora = { version = "0.4.0", features = ["proxy"] }
pingora-core = "0.4.0"
pingora-proxy = "0.4.0"
pingora-runtime = "0.4.0"
ratatui = "0.29.0"
reqwest = { version = "0.12.9", features = ["json", "stream"] }
rust-embed = "8.5.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
tokio-stream = { version = "0.1.16", features = ["sync"] }
url = { version = "2.5.3", features = ["serde"] }
uuid = { version = "1.11.0", features = ["serde", "v4"] }

